### PR TITLE
Types for createComponentClass, Component, and createType

### PR DESCRIPTION
**Pull request by robertlong**
This PR is still a work in progress, but I've added types for `createComponentClass`, `Component`,  and`createType`

### CODE REVIEW

**Comment by snowfrogdev** [comment]
@robertlong @fernandojsg anything I can do to get this PR moving forward?

**Comment by robertlong** [comment]
@snowfrogdev if you have time, you can take this or we can merge it as is. I'm super busy with my other work right now.

**Comment by fernandojsg** [comment]
If this is better than nothing, I'd vote for just merge it and we could improve it in future PRs, what do you think @snowfrogdev @robertlong ?

**Comment by fernandojsg** [comment]
Not relevant anymore, closing it

**Pull request closed without merging**
