### PR TITLE
rewrite into typescript

### PR DESCRIPTION
**Pull request by SonyStone**
I studied the new ECS concept, and began experimenting with this library and transcribed it into typescript.
I forked this library, added what I rewrote, and made "Circles and boxes" and "Intersecting circles" examples work.
If such work is interesting, I can finish it.

Major changes:
* rename `System` to `SystemBase`, because now `System` is interface.
* remove `delta` and `time`, if they are needed, they are easy to add with singleton components.
* rename all `execute` method into `run` to be closer to `amethyst/specs` and  `amethyst/shred` source code.

In the future I intend to:
* finish all the examples and tests.
* remove `SystemBase` completely.
* rename all `queries` to `systemData` or `data` to be closer to `amethyst/specs` and  `amethyst/shred` source code.
* make `queries` parameter of `run()` method
  ```typescript
  run(data: SystemData[]) {
    for (const [circle, position] of data) {}
  }
  ```
* study `amethyst/specs` and  `amethyst/shred` source code deeper to take features from them.

### CODE REVIEW

**Comment by hwaterke** [comment]
Very nice. I was hoping for someone to go on for a typescript rewrite.

Any parts of the code you dropped next to what you already mentioned above?
Any optimisation you added or removed?
Why removing delta and time? They're useful more often than not and are usually part of ECS libs.

**Comment by SonyStone** [comment]
* remove `TagComponent` class, because it was never directly used.
* used `Map` and `Set` in `QueryManager`, `EventDispatcher`, `Entity`, `EntityManager`, `ComponentManager` for faster iteration, search and deleting.
* replace all `for (... in ...)` with `for (... of ...)`
* replace all `for (var i = 0; i < ...; i++) ` with `for (... of ...)`

For now I dropped `RemoteDevTools` folder, because it all was working without it.
I used `Map` and `Set` for optimization. But I did not check performance improvements.
I was thinking, that in systems without `requestAnimationFrame`, `delta` and `time` would be useless.
And in `amethyst/specs` and `yagl/ecs` they used `run(entity)` or `run(data)` with queries as parameter.

For this week my main focus is to make webpack to compile lib bundle and dev-server.

**Comment by SonyStone** [comment]
changes:
* return `System` as class. (In `amethyst/specs` and `amethyst/shred` systems are classes too)
* rewrote tests into Jest.
* made `Three.js` and `Babylon.js` examples work.
* webpack-dev-server for experiments

Now I need to clean up webpack config.
Separate tsconfig for lib, specs and apps. Research `rollup` and `docsify`.
And finally finalize this.

**Comment by snowfrogdev** [comment]
Wow @SonyStone very cool. I'm a TS dev myself and I can appreciate what you are doing here. Alas, I'm wondering if you are not better off simply forking off into another project because, from what I gather, the main author and maintainer of Ecsy, @fernandojsg, is not a TS dev and that would be a big ask for him to completely convert his library to that language. I don't want to speak for him (I kind of am, aren't I 😄) but I think he would prefer we incrementally improve the type definitions in small PRs rather than completely rewrite it in TS. 

@fernandojsg, care to chime in on this. @SonyStone is putting a lot of work into this and I'd hate for him to think it might get merged in any time soon if switching over to TS is not something you are seriously considering at the moment.

**Comment by krazyjakee** [comment]
I'm also lurking this PR and am very excited by the prospect of a rewrite into TS.

**Comment by wingyplus** [comment]
If I understand it correctly. Do we needs to make it support for `mjs` even it rewritten in TypeScript right? I just see this PR removed `mjs` in the example and rewrote it to TypeScript.

**Comment by fernandojsg** [comment]
I appreciate the effort here, although I find it hard to get merge, not just because I'm still not sure about going full typescript, although we have had discussions internally about doing so, we still haven't had a final decision regarding it, but also because this PR is almost rebuilding everything from scratch and I'd expect a more incremental process.
It's not about doing a 1:1 conversion from js to ts, but many things going in the way, like some refactors, changing of folder structure, file names, classes, examples (even they don't use the bundled but need to be bundled as they use ts), and other design decisions that for example are breaking the `ecsy-devtools`.

So honestly not sure how to proceed here so people don't wait for it forever to get merged.
One option could be to merge this to a `typescript` branch instead of using `dev/master` for it, and keep the changes there, or probably at this time creating a fork makes more sense and once we decided if we are going to move forward with ts, we will keep doing an incremental transition.

**Comment by SonyStone** [comment]
@snowfrogdev, @fernandojsg 
Yeah, I think that it would be impossible to merge this rewrite into the main project. I could make it a more incremental process and make a fork where I could go further beyond rewriting.
But on another hand, I do not want to make just another project where I would be a lone developer.

But my plans can go the other way of what this project's current development plans.
Because for now, I want to make this project close to `amethyst` and `amethyst/shred`, put it in monorepo, like `pixi.js`, copy other ecsy projects in this monorepo, and add other tools for game development.
But it's also all new to me, so I still have doubts and lack of knowledge.

@wingyplus Not, it is still generates same bundles, like it was in original. But some names have been changed.

**Comment by FostUK** [comment]
Great work and total apologies for being a naysayer in this case but I have some concerns about converting this project to TS.

* Optimisation is taken away from the project and placed partly in the hands of the Typescript compiler.
* Typescript is still a proprietary standard and requires a build step. What I've particularly enjoyed about this project so far is that it uses straight up ES6 modules - this makes it incredibly easy to develop with (no build needed on modern browsers) and really quick to bundle and tree shake with rollup.

**Comment by SonyStone** [comment]
> Great work and total apologies for being a naysayer in this case but I have some concerns about converting this project to TS.

I made this TypeScript converting to make it easier for me to work with this project. And I wanted to share it.

> * Optimisation is taken away from the project and placed partly in the hands of the Typescript compiler.
> * Typescript is still a proprietary language, not a web standard and it requires a build step. What I've particularly enjoyed about this project so far is that it uses straight up ES6 modules - this makes it incredibly easy to develop with (no build needed on modern browsers) and really quick to bundle and tree shake with rollup.

TypeScript makes it slower? I did not compare performance. And Is It proprietary? It's under Apache License, is it still proprietary?

**Comment by FostUK** [comment]
> TypeScript makes it slower? I did not compare performance. 
Not necessarily - but in converting to Typescript you would give up some control over how things are optimised to the Typescript compiler. E.g: inlining functions, testing if asm.js style shortcutting would improve performance. Specifically with this kind of library it could be really interesting to benchmark. IT would also be interesting to try running it through re-optimisers like Google Closure compiler.

> And Is It proprietary? It's under Apache License, is it still proprietary?
As in - it's not a web standard, and as JS changes, so it might get left behind. See Coffescript.

> I made this TypeScript converting to make it easier for me to work with this project. And I wanted to share it.
Yeah - and I really do apologise - wasn't trying to start a TS vs JS argument or take anything away from the hard work you've done :)

However whilst it might make it more interesting to you - not everyone would necessarily be interested in working on a Typescript version. By your own admission you would prefer not to be sole maintainer of a TS version. I've seen a lot of people trying to push TS conversions PRs to projects then leaving and the orginal maintainers are left with 30-50% more code they have to maintain and a smaller pool of contributers to draw from.

When this has worked I think it's usually been when a project is more mature and a TS fork has been 
maintained alongside it, proven it's worth/support level and then been merged back.

So, for those reasons - my (unaffiliated with the project) opinion would be - this would be better as a fork and see if it gains traction on its own merit rather than pushing TS on the team at this experimental stage.

Of course, to restate - please take my opinion as just one voice and no offence intended :)

**Comment by FostUK** [comment]
> Maintaining a large/complex Typescript codebase is MUCH easier than maintaining a large ES6 one

Yeah that's what people keep saying  :) but we have actually removed Typescript from a fair sized project because we were experiencing the opposite.

In our case - 100% unit test coverage proved to be way more useful for maintaining and refactoring. Refactors in particular were really slow because we would immediately break types and have to ensure correct types when spiking solutions. We were using "strict no any" though which maybe makes things much harder.

Also - I would like to state I'm not anti-TS - the project we removed it from was very user-experience led (gaming platform) so we were more interested in fast iteration on runtime experience rather than correct code at compile time before you've hit live. TS is maybe good for locking down maturing projects or anything critical to be correct before a user ever touches it - like heavy usage web.

Anyway - apologies again - didn't mean this to become some sort of anti-TS rant- just raising the question whether time spent on ts _at this point_ is justified.

**Comment by hwaterke** [comment]
Here are my two cents regarding the discussion.

I think considering typescript for a product or a library (especially an open source one) are two very different things.

TypeScript not only provides safety and compilation checks when writing code, but it is also an always up to date documentation built into the code, which has so many benefits for a library.

Autocompletion in IDEs, ensuring right usage of the defined APIs and contracts the library provides are huge benefits for end users, whether or not the application using it is written in JS or TS.

On top of that, if the TypeScript compilation scares you because it might degrade performances, TypeScript can also be configured to only do type checking and the compilation step does nothing more than removing the types annotations.

You also mentioned rollup for easy bundling and tree shaking. Rollup works with typescript without any problem.

**Comment by robertlong** [comment]
I find the strongest arguments for converting the project to be:

1. Type definition maintenance: Maintaining types alongside a JS codebase is cumbersome and error prone. It's easy to forget to update the typescript definitions alongside a API change. For example, I see this every now and then in Three.js. When the typescript definitions are wrong, this hurts developers using Typescript. When you write the whole library in Typescript, you don't need to worry about this. You can just export types as part of the build process.

2. Project maintenance: Making cross-cutting changes in a Typescript project has, in my experience, been much easier. Typescript isn't perfect by any means, but I find it a very useful tool.

I think @fernandojsg's initial resistance to using TS was flexibility and speed of development. Now that this project is reaching a mature state, I think it makes sense to revisit. I'm happy to help in making the transition should we choose to do so.

**Comment by fernandojsg** [comment]
I understand, and should be obvious, that for typescript developers converting the library to typescript will be more handy and bring a lot of benefits.
But my main concern is that currently number of javascript developers >>> number of typescript developers, and even more, a typescript developer could easily jump right away in a javascript project and start to be productive without any extra knowledge. The opposite is not quite true, and I find myself several times looking for a project, want to collaborate somehow, looking at the code, and... oh damn `.ts` and just give up, because I just don't know typescript.
I know I could just learn typescript and I could be productive and help converting this library and so on, but that's an effort that not everyone willing to help here is probably willing to do.

Apart from that, as you mentioned the library is getting to a mature state, and due the nature of this library, we expect it to keep being small while other bindings and helpers could grow around it, as `ecsy-three`, `ecsy-babylon`, `ecsy-phaser`,... or similar so it's not like are going to be refactoring or adding plenty of features to this one (as opposed to other always-changing frameworks as for example three.js), so I don't see maintaining the ts definition as a big problem. Also the overall size of the library is expected to be really small so this work is totally assumable.

Also currently we can just import the module code as is without any build step needed directly in the browser, using glitch.com for example, and once we get module dependency imports in the browser things will get even easier and won't even need a bundler if you don't want to use it, of course you could do all these build steps or optimizations on your higher level framework using ecsy.

So from my point of view I believe the potential benefits of ts do not exceed the problems it could cause to the js developers (including myself :)) so I tend to go to for the lowest common denominator: javascript + ts definitions.

**Comment by krazyjakee** [comment]
@robertlong If this were a typical web project, I'd side with you but as @FostUK [pointed out](#issuecomment-608536681), there are parts of the typescript compiler that keep you at a distance from the actual JS Engine apis. Performance is so critical to this project that I believe total conversion could be a shot to the foot down the road.

For my project, I would rather have some out-of-date type definitions than risk losing out on performance gains.

**Comment by robertlong** [comment]
Hmm, not sure I agree with the performance argument. There are many performance critical projects including BabylonJS that have optimized Typescript successfully. Should you use only the language features that are supported in your bundle target, you will get a near 1-1 output. The same is true of babel. I've written a few performance sensitive typescript projects now and have very rarely had the output differ enough to matter. Usually these performance issues have to do with async functions and generators which I don't think think the project will use.

Anyway, I think there's enough of a difference in opinion on this issue to warrant keeping the existing manually updated typescript definitions. At the end of the day, if the majority of the contributors to the project would like to avoid writing Typescript, we should avoid using Typescript. PRs that make changes to the public APIs should update the typescript definitions, so authors or reviewers will need to know enough typescript to update those. I'm happy to help with that.

**Comment by fernandojsg** [comment]
> PRs that make changes to the public APIs should update the typescript definitions, so authors or reviewers will need to know enough typescript to update those. I'm happy to help with that.

I agree and I blame myself for not doing that in my PRs, but I promise I'll start learning typescript to change that :)

**Comment by robertlong** [comment]
Yeah, I've got an outstanding PR that needs types as well. I'm also willing to do an audit of our existing typescript definitions and update them as needed.

Let's discuss this issue in our meeting tomorrow and then close this if we're in agreement.

**Comment by Kieirra** [comment]
I feel exactly the same that @fernandojsg, I hope ecsy will stay in javascript (which is the web standard) because I don't like typescript.

However, I will be ok with a migration if there is more typescript contributors than javascript but i don't think it's the case neither.

And to be honest, Typescript vs Javascript is just a matter of personal preference. The real problem is to keep the code & architecture clean and simple when adding functionalities. It's not something really dependent of programming languages I think.

**Comment by fernandojsg** [comment]
I'll be closing it by now so people that arrive here don't get false expectations that we are about to get typescript into the core other than the current approach by introducing types, and we will be using this PR as a reference for anyone asking for a ts rewrite alternative.
This will be an ongoing conversation anyway so if in the future we decide to go back to this and give restart the discussion.
Thank you all for the great feedback, we truly appreciate it and the effort by @SonyStone on this PR!

**Pull request closed without merging**
