### PR TITLE
Speculative change to SystemManager.js Option 1

### PR DESCRIPTION
**Pull request by FostUK**
Allows data to be passed into systems more easily.

Just to get the ball rolling on how to do this.
Currently - because systems are initialised by the SystemManager, it seems difficult to pass data into systems unless created in the init method. An example of this might be passing in the the render method from a display lib.

It looks like the current code is intended to work in the same way as entity code (attributes are used populate class properties) but isn't complete. This makes sense for entities which should be used to store data. However systems will inevitably have more complicated requirements. Also - assigning properties to the system class starts pushing people down the route of sharing data on the class - which may not be what you want if you are trying to avoid classes.

By passing any attributes into the init function this would allow developers to handle additional system data in any way they see fit.

Note: added a test but am new to Ava so may need some guidance there.

**TODO**
* Docs

### CODE REVIEW

**Comment by FostUK** [comment]
Any feedback on either of this or #152? So I can finish them off or abandon?

Have made a quick demo (work in progress here: https://www.bbc.co.uk/games/embed/genie-ecsy-demo?versionOverride=latest&viewNonPublished=true )

 but couldn't seem to get very far without the functionality to pass data to systems on creation so the above uses my modified version of Ecsy,

If people are doing this in another way then I might switch to looking at improving docs as it's the one area I've had trouble with.

**Comment by fernandojsg** [comment]
@FostUK sorry for the delay! I was about to review it today as we are planning some changes on the API and I wanted to wait until the decision on these changes in order to decide which one would fit better. 
I'll let you know later today ;) thanks for your work!

**Comment by fernandojsg** [comment]
@FostUK btw I got this 
```Sorry, this game can only be played if you are in the UK.
You're seeing this page because it looks like you're outside of the UK. If you're in the UK, please check your browser and try again. If that still doesn't work, there may be a problem with your internet connection.
``` 

Any way I could test that (I'm in Spain) :)

**Comment by FostUK** [comment]
@fernandojsg - that's cool thanks! 

Forgot about the work geoblock. I'll see if I can post a link that skips it.

**Comment by FostUK** [comment]
This might work for you: https://www.test.bbc.co.uk/games/embed/genie-ecsy-demo?versionOverride=latest&viewNonPublished=true&isUk=true

- cursor keys to move
- pick up eggs to get bigger
- eat dinosaurs smaller than you.

**Comment by fernandojsg** [comment]
@FostUK the game looks great! it's quite addictive, nice job. (although I found an "issue" as I tried to kill them all in the first rounds and the game just ends without any new dinosaur appearing). This could be also a really good use case for multiplayer where each dinosaur is an user isn't it? :D

**Comment by FostUK** [comment]
Yeah multiplayer with lots of eggs would be great!

It's mainly a tech demo to see how ecsy would integrate with our tools but I keep adding things when I have the time - which is a good indication of Ecsy's ease of use. :)

**Comment by fernandojsg** [comment]
> Yeah multiplayer with lots of eggs would be great!
> 
> It's mainly a tech demo to see how ecsy would integrate with our tools but I keep adding things when I have the time - which is a good indication of Ecsy's ease of use. :)

That's supercool! Looking forward for more feedback and demos from you ^_^

Re this issue, have you checked my comment https://github.com/MozillaReality/ecsy/issues/145#issuecomment-634291209 ? Apart from using the constructor I like both approaches honestly, no strong opinion here:
- #151 `init(attributes)` it's cool because we don't force the user any new concept, you will just get the attributes there and you can use them or not
- #152 setting the `system[attrName] = attrValue` seems also handy as probably you will be doing the same anyway on your constructor, so a bit of syntactic sugar. I just have concerns with the `system.copy()` method you used as optional there, as is a new concept and it can be confusing what to expect from that method

**Comment by FostUK** [comment]
Yeah - I have mixed feelings on both of these too - I've tried both out and I think prob the sensible route api-wise would be #152 as it is consistent with the way attributes are copied onto components.

I liked #151 though purely because with system code it was nice to get away from the class coupling and this makes it marginally easier;  you can still unravel the class with #152 though.
Also it's passed in and you can do what you want with it - like you say - if you want a shallow or a deeper copy you can implement that yourself.

**Comment by fernandojsg** [comment]
@FostUK ok merging it by now, as It could be more useful for most people and we could still document the calling the constructor way if they want to do it (across with adding support for ts to do that #155) 
Thanks a lot! And please keep us updated with your work, we are excited about it! ;)

**Pull request merged**
