### PR TITLE
Make getComponent use an optional return type

### PR DESCRIPTION
**Pull request by robertlong**
`getComponent`, `getRemovedComponent`, and `getMutableComponent` now use optional return types. This lets you use the `entity.getComponent!(MyComponent)` syntax when using Typescript's strict mode instead of `entity.getComponent(MyComponent) as MyComponent`.

### CODE REVIEW

**Comment by sheepsteak** [comment]
@robertlong thanks for working on the TypeScript types. I just wondered why `?` was added to the function names since that is stating that the functions themselves are possibly undefined (which of course they're not because they'll always be there 😄).

If it was:

```js
  getComponent<C extends Component<any>>(
    Component: ComponentConstructor<C>,
    includeRemoved?: boolean
  ): Readonly<C> | undefined;
```

then you could still do `entity.getComponent(MyComponent)!` or `entity.getComponent(MyComponent)?.value` which I think makes more sense as to what's happening. Either way in strict mode you need `!` but at least it would be in a place that probably makes more sense to most people.

People using non-strict mode should be unaffected.

What do you think?

/cc @fernandojsg

**Comment by robertlong** [comment]
@sheepsteak I tried what you suggested and the compiler said that was invalid. Have you tested it? If what you're saying is true then yes I would rather do it that way. The same is true for the `getObject3D` method.

**Comment by robertlong** [comment]
Nvm I just tested it. I must have been running into another issue then.

This works as I'd expect
```typescript
interface Test {
  test: number | undefined
  test2(): number | undefined
}

const a: Test = {};

a.test! += 1;
const y = a.test2()! + 1;
```

**Comment by mmahandev** [comment]
If these methods would never be undefined in the first place why are they set as optional? I'm not understanding why the type builds it out so that `!` is mandatory on strict mode.

**Pull request merged**
