### PR TITLE
Add world to System.d.ts

### PR DESCRIPTION
**Pull request by Kieirra**
Just a little PR to add 'world' member to System.d.ts to fix intellisense error when using this.world into System object.

### CODE REVIEW

**Comment by Nebual** [comment]
:+1:, though I found making World extendable was useful: https://github.com/Nebual/ecsy/commit/6bb159393611587e7ca4ac389c9165baa6b20ba0#diff-0a5754ffaffe5e62adb7fff88db38e1d

**Comment by Kieirra** [comment]
Hi Nebual,
Mm... I'm curious to know why it's better to make World extendable (I'm not a typescript guy).
It cannot be anything more than World in the current codebase I'm wrong ?

**Comment by fernandojsg** [comment]
Thanks!

**Comment by Nebual** [comment]
Thanks for merge!

@Kieirra I stumbled on that commit I linked authored by someone else, not sure what use they had for it (or how common this pattern is in TS), but I extended World to add my websocket connection manager: https://github.com/Nebual/space-couch/blob/a749d3df9ff7a0bc87709b48a75746270ce36714/src/server/Game.ts#L29 so my Systems could send network requests (informing clients of the new state) https://github.com/Nebual/space-couch/blob/a749d3df9ff7a0bc87709b48a75746270ce36714/src/server/Systems.ts#L267

**Comment by Kieirra** [comment]
Interesting, thanks for the answer.

**Pull request merged**
