### PR TITLE
Check for existance of window object

### PR DESCRIPTION
**Pull request by aigan**
This will let you use ECSY in Web Workers or Node.
Keeping RemoteDevTools if run in main browser thread.

### CODE REVIEW

**Comment by aigan** [comment]
fixes #156 and #130

**Comment by Kieirra** [comment]
Oh really nice, need it on Node.

**Comment by Kieirra** [comment]
I tested your fix on node, unfortunately you need to get rid of 'performance' object too if you want to make it works on nodejs.

For instance : ```this.lastTime = performance.now();```  in World.js

**Comment by Kieirra** [comment]
Date.now() seems to be a good replacement since it works on node server and client side no ?

**Comment by FostUK** [comment]
@Kieirra which version of node are you using? Looks like performance.now is available since 8.5:

https://nodejs.org/api/perf_hooks.html#perf_hooks_performance_now

**Comment by FostUK** [comment]
Ahh - you have to require perf_hooks:
`const { performance } = require('perf_hooks');`

Is there a way we can make the require only if running under node?

**Comment by Kieirra** [comment]
I'm on v13, to use performance.now() you need to : require('perf_hooks'). Not sure it will work on client side if you add it.

**Comment by aigan** [comment]
Ok. Added a minimal polyfill for nodejs.

**Comment by fernandojsg** [comment]
I was just hitting this issue few days ago mainly related to the tests. I was fixing it by using: https://github.com/MozillaReality/ecsy/pull/164 
Usually I'd prefer to avoid adding anything to node's `globals` as it could have side effects.
I hope you don't mind that I'm closing it in favor of mine as the other one includes other fixes too.
Thanks for the help!

**Pull request closed without merging**
